# Generated by Django 5.0.6 on 2024-06-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CelebralEnigmaBlog', '0003_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
