# Generated by Django 5.0.6 on 2024-07-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CelebralEnigmaBlog', '0008_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
