# Generated by Django 5.0.6 on 2024-07-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CelebralEnigmaBlog', '0009_emailsubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubs',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
